# Generated by Django 3.1.2 on 2020-11-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.DecimalField(decimal_places=1, default=0.1, max_digits=3)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('visited', models.BooleanField(default=False)),
                ('visited_on', models.DateField()),
                ('difficulty_level', models.IntegerField(default=0)),
                ('my_rating', models.IntegerField(default=0)),
                ('top_ten', models.BooleanField(default=False)),
            ],
        ),
    ]
